<a href="https://colab.research.google.com/github/chacha86/pythonai2/blob/main/%ED%8C%90%EB%8B%A4%EC%8A%A4_%EA%B8%B0%EC%B4%882_%EC%A0%95%EB%A0%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [4]:
df1 = pd.read_excel('/content/거래내역조회 (3).xlsx', skiprows=3)
df2 = pd.read_excel('/content/students (2).xlsx')

In [ ]:
df1.loc[0]
df1.loc[:,'거래일시']

df1.loc[[0, 2, 5]]
df1.loc[:, ['거래일시', '취급점', '찾으신금액']]
df1.loc[[0, 2, 5], ['거래일시', '취급점', '찾으신금액']]

In [ ]:
# 6. 정렬
df1

## 6.1 시리즈 정렬
df1['찾으신금액'].sort_values(ascending=False)

## 6.2 데이터 프레임 정렬
df1.sort_values("찾으신금액", ascending=True) # 찾으신금액 오름차순
df1.sort_values("찾으신금액", ascending=False) # 찾으신금액 내림차순

df1.sort_values("기재내용", ascending=True) # 기재내용 오름차순
df1.sort_values("기재내용", ascending=False) # 기재내용 내림차순

df1.sort_values(["적요", "찾으신금액"], ascending=[True, False]) # 적요로 오름차순, 찾으신금액 내림차순

## 6.3 인덱스로 정렬
df1.sort_index(ascending=False)

In [35]:
# 7. 위에서 자르기, 아래서 자르기
## 7.1 위에서 자르기(기본 5개)
df1.head()
df1.head(8)

## 7.2 아래서 자르기(기본 5개)
df1.tail()
df1.tail(7)

   No.              거래일시    적요    기재내용   찾으신금액   맡기신금액  거래후 잔액        취급점  메모
3    4  2022.03.10 16:05  체크우리    스타벅스    2000       0  158193  영업추진부(카드) NaN
4    5  2022.03.10 10:42  체크우리  몸짱피트니스  238000       0  160193  영업추진부(카드) NaN
5    6  2022.03.10 10:40  타행이체      친구       0  100000  398193       KB증권 NaN
6    7  2022.03.10 00:59   펌뱅킹    이커머스   15540       0  198193     유성금융센터 NaN
7    8  2022.03.09 18:49  체크우리     커피집    2000       0  213733  영업추진부(카드) NaN
8    9  2022.03.09 18:05  타행이체      가족       0  200000  215733       KB증권 NaN
9   10  2022.03.09 16:52  체크우리     피자집    9800       0   15733  영업추진부(카드) NaN